

name: Deploy angular portfolio

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Setup Node
       uses: actions/setup-node@v4

     - name: Install Dependencies
       run: npm install

     - name: Build app
       run: npm run build

     - name: Artifact upload
       uses: actions/upload-pages-artifact@v3
       with:
        name: github-pages
        path: dist/portfolio/browser


  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to github
        id: deplyment
        uses: actions/deploy-pages@v4


